on:
  pull_request: null
  push:
    branches:
      - '3.x'

name: testo

permissions:
  contents: read

jobs:
  testo:
    uses: spiral/gh-actions/.github/workflows/testo.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      run: vendor/bin/testo --suite=Unit
